# Bidirectional Sequence Models - Lab

## Introduction

In this lab, we'll learn to make use of **_Bidirectional Models_** to better classify sequences of text!

## Objectives

You will be able to:

* Understand and explain the basic architecture of a Bidirectional RNN. 
* Identify the types of problems Bidirectional approaches are best suited for. 
* Build and train Bidirectional RNN Models. 

## Getting Started

In this lab, we're going to use a **_Bidrectional LSTM Model_** to build a model that can identify toxic comments on social media. This dataset comes from the [Toxic Comment Classification Challenge on Kaggle](https://www.kaggle.com/c/jigsaw-toxic-comment-classification-challenge) in partnership with Google and Jigsaw.

## The Problem

From the "Data" section of the Kaggle competition linked above:

"You are provided with a large number of Wikipedia comments which have been labeled by human raters for toxic behavior. The types of toxicity are:

* toxic
* severe_toxic
* obscene
* threat
* insult
* identity_hate

You must create a model which predicts a probability of each type of toxicity for each comment."

This tells us a couple things about the problem, which will affect the overall architecture of our model. Although this may technically be a multiclass classification problem, in practice, our model will treat each comment as 6 concurrent instances of binary classification. This is because a toxic comment can fall into one or more of the categories listed above--for example, a  comment may be toxic, obscene, threatening, and insulting, all at the same time. 

Run the cell below to import everything we'll need for this lab. 

In [1]:
import pandas as pd
import numpy as np
np.random.seed(0)
import matplotlib.pyplot as plt
%matplotlib inline
import keras
from keras.preprocessing.sequence import pad_sequences
from keras.layers import Input, Dense, LSTM, Embedding
from keras.layers import Dropout, Activation, Bidirectional, GlobalMaxPool1D
from keras.models import Model
from keras import initializers, regularizers, constraints, optimizers, layers
from keras.preprocessing import text, sequence
from keras.callbacks import ModelCheckpoint
from keras.callbacks import EarlyStopping

## Loading the Data

We'll start by loading in our training and testing data. You'll find the data stored inside of the file `data.zip` included in this repo. 

**_NOTE:_**  Before we can begin loading in the data using pandas, you'll first need to unzip the file. Go into the repo you've cloned and unzip the `data` folder into the same directory as this jupyter notebook now.

Next, we'll use pandas to load in our training and testing data, and then downsample to only 20% of the training data, in the interest of training time. 

In the cell below:

* Use pandas to read the training data from `data/train.csv`. Store this data in `train`.
* Set `train` equal to `train.sample(frac=0.2)`, so that we'll only use 20% of the data to train our model. Otherwise, training this model could take several hours. 

In [16]:
train = pd.read_csv('data/data/train.csv')
train = train.sample(frac = .2)

In [17]:
train

id                                       comment_text  \
138108  e30cddf768ba4511  Please stop trying to scare me away with these...   
97748   0aefdde2c22f95b6  April 2009 (UTC)\n\nYeah, its stupid to even r...   
109618  4a540571bfeedd1b  PapaJoeGames\n\n   PapaJoeGames was founded by...   
31964   54ea1c3ba6382b76  Aside from the municipal election, I don't kno...   
135709  d5c31424253e76b1  What a bunch of BS, banned for stating the tru...   
69763   baa629b6357ed5fa  May 2009 (UTC)\nThanks for dealing with that p...   
90529   f23b11d5b57512e7                        I misread it; my apologies.   
89214   eeaa18dea433bba0  message re your last change, go fuck your self...   
22788   3c2f42f0a4c3e0f9  "I'd appreciate if i could be un-blocked now, ...   
36891   6282f1c1f5afcc66  Clean up\nI can't stand reading this - spellin...   
43596   74650b87f1bbde99  "\n\n Thank you! \n\nLogan, thank you so much ...   
135231  d347b4cfbe910e01  Welcome!\n\nHello, , I am   and it is my pleas...   
121119  87fc7beb1f6056a1  You're right, I've looked at it a million time...   
82348   dc4d8b811ad683e3  Its so simple. If you have a proxy located in ...   
23307   3d8e1d2d997b79e3  Tsunami Reports \n\nEvidence is mounting that ...   
70744   bd51acc8c396aa09  "\n\nWrong:  Jeffers' travels were extensive. ...   
24000   3f63a4c909c980ed  Sahibe Kamaal Sri Guru Gobind Singh book\nBatt...   
71650   bfd4f2f5b355466f  Thanks for your comment, it is gratifying that...   
69810   bac30d18114283f0  WoWpedia \n\nWowpedia is now at AfD.  I left a...   
91922   f5bd938fac0518e6  Franklin's Saying Arranged By Subject \n\nSond...   
15994   2a30c8efc06485f9  Perhaps he will find comfort alone, in a shack...   
121924  8c45fd5b499859a5         REDIRECT Talk:Alex Davies (snooker player)   
130562  ba71b3f8a375c1b0  September 2014 \n\ni did not leave any comment...   
95689   ffe78922d780fdb5  "\n\n Right to vanish \n\nSee the article Wiki...   
52852   8d476c10c62f67c1  TNA said he is the first champion of the TNA e...   
50215   8638e0ea96581ad4  "*Well I cannot respond to this over at deleti...   
71711   bffe6cc3a60ad0fe  THE HORIZONTAL WHITE LABEL WAS AN EARLY PRINTING!   
79476   d4a81de0018d6383  (UTC)\n\n I agree with User:Man with two legs ...   
148419  4c1b76770ae5d20a  Oh and do the research myself? I don't fucking...   
66598   b239cc0110d06959  Hi, back. I'll leave these bot messages becaus...   
...                  ...                                                ...   
138269  e3e073db2bcf7058  "\n\n Hugo Margenat \n\nFound an Image Tony, A...   
115355  68dca1b875cd9a59                              |listas = Hahn, Erwin   
1930    053b24b25f48a5e7  Pursuant to the Wikipedia's policy on biograph...   
73731   c54c4aab8c84307c  message \n\nDr. Dre really is 48 years old  bo...   
49453   843bfba4869c3790  So is that it Jimmy? - is that the policy that...   
28557   4b9ce8bc13fa2531  Hitler's sexuality\nPlease do not add nonsense...   
151402  7c7d5fd71deb63b2  The arrogant dlckhead is retired\nhe and some ...   
77008   ce3c2c946c7f379d  ":Just a suggestion...  The economist William ...   
107681  3fa6324f606c63e8  Nice enhancements to the article. \nI will be ...   
85225   e3fe5279ac3c2af3  Thank you for experimenting with the page Over...   
20689   369beb4906171497  im not vandalizing \ni made changes to the lis...   
155189  ba374864b03f6978  this article fails to explain camphene's contr...   
45036   78665b44bd15d4f0  u suck!!!! \n\nWUTS YOUR PROBLEM U NERD. I JUS...   
63064   a8b650847040f808  Guns N' Roses Family Tree \n\nIs there a reaso...   
150769  71bf6ff9f896b2c5  I disagree with you. In terms of Glass-Steagal...   
66508   b1f227f75b50eda2  "Welcome!\n\nHello, , and welcome to Wikipedia...   
70325   bc25ba2ade8ef8ae  Medium Pimpin & Live Prayer \n\nHi Merope,\n\n...   
135088  d292cbaca86b0b58  "\n\n Dropping out \n\nI'm Dropping out of the...   
87343   e9b13c9b507a0c0e  "\n\nArchives Archive 1: July 2004\n Archive 2

Great! Next, we'll get the values for both our labels and the comments that will act as our training and testing data. We do this in order to get the data from pandas DataFrames to numpy arrays. 

In the cell below:

* Create an array called `list_classes` that contains the following classes, in this order:
    * `'toxic'`
    * `'severe_toxic'`
    * `'obscene'`
    * `'threat'`
    * `'insult'`
    * `'identity_hate'`
* Store the `.values` of the DataFrame that is returned by using `list_classes` to slice the label columns from `train` (slice `list_classes` from train, and then chain it with `.values`). Store this in `y`.
* Store the `.values` of `train['comment_text]` in `list_sentences_train`

In [18]:
list_classes = ['toxic',
                'severe_toxic',
                'obscene',
                'threat',
                'insult',
                'identity_hate']
y = train[list_classes].values
print(y)
list_sentences_train = train['comment_text'].values
print(list_sentences_train)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 ...
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
['Please stop trying to scare me away with these overwhelming messages and ANs. Am I being arrested for making edits to Wikipedia?'
 "April 2009 (UTC)\n\nYeah, its stupid to even request deletion for an article of a musical genre that has existed for over ten years. Should we delete Post-Grunge as well? How about deleting Rapcore? It would be the same as deleting this article. If something isn't perfect you don't throw it away, you improve it.75.139.103.133  16:55, 18"
 "PapaJoeGames\n\n   PapaJoeGames was founded by Akash Hundal in 2009. He was 10 when he started it. Born January 10, 1999 in Turlock, California. He got into a GATE class at age 9. His parents, Harinder and Bhupinder Hundal, own a really successful restaurant in Modesto, California. It's named Royal India Indian Cuisine. He also has 2 sister named Rikku and Rumeet Hundal. Rikku born November 15 1994 and Rummet born in January

According to the data dictionary for this Kaggle competition, there are no missing values in either the train or the test set. However, let's quickly double check, just to be sure!

Run the cell below to see if there are any missing values in either the training set.

In [19]:
# Double check that there are no missing values in either training set
train['comment_text'].isna().any() 

False

## Preprocessing The Data

Next, We'll need to preprocess our data. We've already learned how to do most of this by working with NLTK--however, keras also contains some excellent preprocessing packages to help prepare text data.  Since we'll be feeding this data right into a model built with keras, this has the added benefit of ensuring that our data will be in a format that our model will be able to work with, meaning that we can avoid the weird bugs that sometimes occur when working with multiple different 3rd party libraries at the same time. 

Our preprocessing steps are:

1. **_Tokenize_** the data. 
2. Turn the tokenized text into **_Sequences_**
3. **_Pad_** the sequences so they're all the same length. 

In the cell below:

* Create a `Tokenizer`, which can be found inside the `text` module we imported at the top of the lab. Set the `num_words` parameter to `20000`, so that our model only uses the 20000 most common words. 
* Convert `list_sentences_train` to a python list, and then pass it in to our tokenizer's `.fit_on_texts()` method. 
* Call the tokenizer's `texts_to_sequences()` method on `list_sentences_train` and store the result returned in `list_tokenized_train`
* Use the `sequence` module's `pad_sequences()` method and pass in `list_tokenized_train`, as well as the parameter `maxlen=100`. Store the result returned in `X_t`.

In [22]:
# NOTE: This cell may take a little while to run!
tokenizer = text.Tokenizer(num_words=20000)
tokenizer.fit_on_texts(list(list_sentences_train))
list_tokenized_train = tokenizer.texts_to_sequences(list_sentences_train)
X_t = sequence.pad_sequences(list_tokenized_train, maxlen=100)

## Creating Our Model

Now that we've loaded and preprocessed our data, we're ready to begin designing our model. By now, working with keras to create and compile a model will probably feel familiar to you. To keep things simple, we've left the name of each layer below. Your job will be to create each layer, and specify the previous layer that acts as it's input (which is why so many of the layers are called `x` below--you've probably noticed this simplifies the creation process by eliminating the need to keep track of which layer is which at any given point). 

In the cell below:

* Set the `embedding_size` to `128`
* Create an `Input` layer that takes in data of `shape=(100,)`
* Next, create an `Embedding` layer and pass in `20000` and `embedding_size` as parameters. Make sure to specify that the Embedding layer takes in the output of the input layer as its input by ending the line with `(input_)`
* Create a `Bidirectional` layer. Inside this layer, pass in an `LSTM()`. The parameters for the LSTM should be `25`, and `return_sequences=True`. 
* Create a `GlobalMaxPool1D` Layer
* Create a `Dropout` layer, and pass in `0.5` as a parameter. 
* Create a `Dense` layer with `50` neurons, and set the `activation` to `'relu'`
* Create another `Dropout` layer, and pass in `0.5` as the parameter. 
* Create a `Dense` layer with `6` neurons, and set the `activation` to `'sigmoid'`. 
* Create a `Model` and set the `inputs` to `input_` and `outputs` to `x`.

In [25]:
embedding_size = 128
input_ = Input(shape=(100,))
x = Embedding(20000, embedding_size)(input_)
x = Bidirectional(LSTM(25, return_sequences = True))(x)
x = GlobalMaxPool1D()(x)
x = Dropout(rate = .5)(x)
x = Dense(50, activation = 'relu')(x)
x = Dropout(rate  = .5)(x)
x = Dense(6, activation = 'sigmoid')(x)

model = Model(inputs = input_, outputs = x)

In [ ]:
embedding_size = 128
input_ = Input(shape=(100,))
x = Embedding(30000, embedding_size)(input_)
x = Bidirectional(LSTM(25, return_sequences=True))(x)
x = GlobalMaxPool1D()(x)
x = Dropout(0.5)(x)
x = Dense(50, activation='relu')(x)
x = Dropout(0.5)(x)
x = Dense(6, activation='sigmoid')(x)

model = Model(inputs=input_, outputs=x)

Great! Now that we've created our model, we still need to compile it.  

In the cell below:

* Call `model.compile` and pass in the following parameters:
    * `loss='binary_crossentropy'`
    * `optimizer='adam'`
    * `metrics=['accuracy']`

In [26]:
model.compile(loss = 'binary_crossentropy',
             optimizer = 'adam',
             metrics = ['accuracy'])

Now, let's take a look at the model we've created. In the cell below, call `model.summary()`.

In [27]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         (None, 100)               0         
_________________________________________________________________
embedding_2 (Embedding)      (None, 100, 128)          2560000   
_________________________________________________________________
bidirectional_2 (Bidirection (None, 100, 50)           30800     
_________________________________________________________________
global_max_pooling1d_2 (Glob (None, 50)                0         
_________________________________________________________________
dropout_3 (Dropout)          (None, 50)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 50)                2550      
_________________________________________________________________
dropout_4 (Dropout)          (None, 50)                0         
__________

## Setting Some Checkpoints

Training models like this can be tricky. Because of that, we'll make use of **_Checkpoints_** to help us periodically save our work in case things go wrong during training. 

We'll create two different types of checkpoints below:

* A `ModelCheckpoint` that saves the best weights for our model at any given time inside an `hdf5` file. This way, if our model's performance starts to degrade at any point, we can always reload the weights from a snapshot of when it had the best possible performance. 

* An `EarlyStopping` checkpoint, which will stop the training early if the model goes for a certain number of epochs without any progress. 

For this lab, we'll only be training the model for a single epoch, so we don't actually need to use these checkpoints. However, on the job, models like this are often trained for days at a time. With training times that long, checkpoints are absolutely crucial to avoid losing days of work. There are few things more frustrating than seeing that you model was performing really well 2 days ago, but has since began to have performance degrade due to overfitting, and you have to start the training over because you forgot to set checkpoints!

Run the cells below to create the checkpoints and store them in an array that we'll pass in during training. For more information on the checkpoints we've created, see the [Keras callbacks documentation](https://keras.io/callbacks/#earlystopping).

In [28]:
checkpoints_path = 'weights_base.best.hdf5'
checkpoint = ModelCheckpoint(checkpoints_path, monitor='val_loss', verbose=1, save_best_only=True, mode='min')

In [29]:
early_stopping = EarlyStopping(monitor='val_loss', mode='min', patience=25)

In [30]:
callbacks = [checkpoint, early_stopping]

## Training the Model

Now, we're ready to train our data. Because our model contains over 1.9 million trainable parameters, this will take a little while to train! 

In the cell below:

* Call `model.fit()` and pass in the following parameters:
    * `X_t`
    * `y`
    * `batch_size=32`
    * `epochs=1`
    * `validation_split=0.1`
    * `callbacks=callbacks`
    
**_NOTE:_** Running the cell below may take 15+ minutes, depending on your machine. Run it, then go get a coffee!

In [ ]:
model.fit(X_t, y, batch_size= 32, epochs=1, validation_split=.1, callbacks=callbacks)

Instructions for updating:
Use tf.cast instead.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
Train on 28722 samples, validate on 3192 samples
Epoch 1/1
23584/28722 [=======================>......] - ETA: 19s - loss: 0.1426 - acc: 0.9593

Validation accuracy of over 97.8% when trained on only 20% of the data--this is excellent! If you train on the entire training set, you'll see that we achieve over 98% accuracy after only 1 epoch of training. It's safe to say our model works pretty well!

## Summary

In this lab, we incorporated everything we've learned about sequence models and embedding layers to build a Bidirectional LSTM Network to successfully classify toxic comments from wikipedia!